### ISSUE TITLE
Hosted asset bundle for 1.0a10 is structured improperly

### ISSUE THREAD

**Issue by dheavern** [philkr/pystk#17]
**Describe the bug**
Pystk will segfault when using the latest version.  The new asset bundle is incomplete and fails some consistency checks.  I have been able to workaround it temporarily by using the full asset bundle from a full version of SuperTuxKart.  Presumably this workaround bundle also includes unnecessary assets and differs slightly from the official pystk assets.

**To Reproduce**
Clean install via pip then attempt to run examples/play

**Comment by dheavern** [comment]
I investigated this a little deeper, its not actually a problem with the asset bundle but with its structure.  I believe if the contents of /stk-assets/ are moved to the top level of the zip then the bundle should work.

**Comment by philkr** [comment]
thank you! Fixed the hosted assets zip.
