### ISSUE TITLE
segmentation fault while pystk.init(config)

### ISSUE THREAD

**Issue by jedi2610** [philkr/pystk#33]
**Describe the bug**
crashes while initializing env with config.

**To Reproduce**
```python
➜  ~ ipython
Python 3.9.4 (default, Apr 20 2021, 15:51:38)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pystk

In [2]: config = pystk.GraphicsConfig.hd()

In [3]: pystk.init(config)
zsh: segmentation fault (core dumped)  ipython
➜  ~
```

**System information:**
 - OS: linux
 - CPU: ryzen 5 2600
 - GPU: radeon rx 580

**Comment by jedi2610** [comment]
here is a dump of the traceback.
```python
Python 3.9.4 (default, Apr 20 2021, 15:51:38)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faulthandler
>>> import pystk
>>> faulthandler.enable()
>>> config = pystk.GraphicsConfig.hd()
>>> pystk.init(config)
Fatal Python error: Segmentation fault

Current thread 0x00007f6e8dabf740 (most recent call first):
  File "<stdin>", line 1 in <module>
zsh: segmentation fault (core dumped)  python3
```

**Comment by jedi2610** [comment]
@philkr after reading this [thread](https://stackoverflow.com/a/13654489) i guess it's because this is a port from c to python.

**Comment by jedi2610** [comment]
@philkr okay i just tried the same on my windows machine and it works. any thoughts on why that might be?

**Comment by philkr** [comment]
It's likely the AMD driver and EGL. I don't have an AMD GPU to debug
though...

**Comment by jedi2610** [comment]
@philkr but i'm dual booting linux and windows so i have the same gpu. ofc the drivers would be different but i was wondering if that's whats causing the problem.

**Comment by jedi2610** [comment]
@philkr but the actual SuperTuxKart game is working fine. did you change the code related to drivers or something?

**Comment by JonathanJao** [comment]
Hi, I'm also experiencing this issue on my machine. My CPU is Core i5, OS is Debian Linux, with no dedicated GPU. I tried on another one of my machines with a Intel Pentium CPU, Debian Linux, and Nvidia GTX 1080 Ti, and it also seemed to throw a segmentation fault. Is there some diagnosis process here or fix available? Thanks!

**Comment by notjedi** [comment]
i have a 1660, it works fine now. so i don't think i can do much here.

**Comment by codinguncut** [comment]
I had the same issue and managed to resolve it.
Hopefully the below steps were what fixed it ;)

### Environment:
```
^C(base) paperspace@pstd8xkqxplf:~$ nvidia-smi
Tue Jan 23 11:25:49 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A4000    Off  | 00000000:00:05.0 Off |                  Off |
| 31%   56C    P0    41W / 140W |      0MiB / 16376MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

Distribution: `Ubuntu 22.04.2 LTS`

I had run `pip install PySuperTuxKart` before installing libegl, and my hypothesis is that this may have caused the problem (maybe a linking issue)

- `conda install -c anaconda mesa-libegl-cos6-x86_64`
- (I also ran `sudo apt-get install libegl-mesa0 libegl-dev`, not sure if that made a difference)
- `pip install --reinstall PySuperTuxKart`

This (I think) solved the issue for me.

**Comment by Gclabbe** [comment]
The sudo apt-get was required for mine on Ubuntu 23.10 with NVidia CUDA 11.7 and NV driver 535
