### ISSUE TITLE
Error installing via pip?

### ISSUE THREAD

**Issue by junxiant** [philkr/pystk#40]
Error installing when trying to install via pip

```
pip install PySuperTuxKart
pip install PySuperTuxKart --no-cache-dir
```
rm -rf ~/.cache/pip and rerunning the pip install still didn't work. 

![image](https://github.com/philkr/pystk/assets/25401067/94abdd37-4984-49a3-8462-4f440a3b2501)

**Comment by turnerluke** [comment]
What version of Python are you using? I only got the installation to work on Python 3.9.6

**Comment by junxiant** [comment]
Sorry I forgot to mention it is python 3.8

**Comment by rwbakerUMASS** [comment]
Having the same issue with python 3.12.2

**Comment by rwbakerUMASS** [comment]
Downgrading to Python 3.9.6 seems to have fixed the issue
